-- 코드를 작성해주세요
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO AS PARENT
JOIN ITEM_TREE AS T ON PARENT.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS CHILD ON T.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC